### ISSUE TITLE
About evaluating the FLOPs

### ISSUE THREAD

**Issue by CheungBH** [psh150204/FBS#3]
Hello. Thanks for your code and it works. 
I wonder that do you have the coding evaluating the FLOPs?

**Comment by CheungBH** [comment]
I also have some confusion about the inference code. I found that in the fbs_forward() function, the convolution is not processed with the masks. 
https://github.com/psh150204/FBS/blob/40aed2d3a10d592b3f83f106a9bccafff1184ec3/model.py#L43
However, in the paper, the convolution is conducted based on the masks. 
I wonder why it is?

**Comment by siihwanpark** [comment]
Thank you for your interest in my work.

1. Sorry I have no code for evaluating the FLOPs
2. From line 45-49, if the forward is in inference mode, there is a masking procedure

**Comment by CheungBH** [comment]
Thanks for your reply.
So in this code, the FBS can not achieve acceleration, right? Because the samples still needs to conduct the complete inference of the model and the additional masking layers. There is not any channel selections, weight indexing and copy operations.
If using in the real-world acceleration, we need special hardware design to achieve it. Is it right?

**Comment by siihwanpark** [comment]
Yes you're right. This work only simulates the effect of pruning, not actually pruning. If you want to do so, you need some extra work on saving pruned model explicitly.

**Comment by CheungBH** [comment]
> Yes you're right. This work only simulates the effect of pruning, not actually pruning. If you want to do so, you need some extra work on saving pruned model explicitly.

Thanks for your explanation!
BTW, I am comparing the metric shown in the paper and the code, and I found that there is a gap between them.
As for the sparsity ratio [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], the proposed accuracy in the paper is around 
[0.88, 0.9, 0.905, 0.91, 0.916, 0.917, 0.918, 0.919] (shown in the graph). 
However, my accuracy is 
[0.828, 0.8517, 0.8565, 0.8613, 0.8681, 0.8705, 0.8697, 0.8729]. The trend is similar, but the accuracy value is 4-5% lower. 
Is the result similar to yours?

**Comment by siihwanpark** [comment]
Yes. Since it was a kind of practice, I focused on checking the tendency rather than completely reproducing the performance in the paper.

**Comment by CheungBH** [comment]
Thank you. I am clear now
